import {
  jijinImg,
  hongsuImg,
  sansataeImg,
  gamumImg,
  taepoongImg,
  thunderImg,
  gangponngImg,
  hanpaImg,
  hwangsaImg,
  ohnamiImg,
  pokyumImg,
  hwasanImg,
} from "../../public";
export const arr = [
  { src: jijinImg, comment: "지진", path: "earthquake" },
  { src: thunderImg, comment: "낙뢰", path: "thunderstroke" },
  { src: hongsuImg, comment: "호우", path: "flood" },
  { src: sansataeImg, comment: "산사태", path: "landslide" },
  { src: gamumImg, comment: "가뭄", path: "drought" },
  { src: taepoongImg, comment: "태풍", path: "typhoon" },
  { src: gangponngImg, comment: "강풍", path: "gale" },
  { src: hanpaImg, comment: "한파", path: "coldwave" },
  { src: hwangsaImg, comment: "황사", path: "duststorm" },
  { src: ohnamiImg, comment: "쓰나미", path: "tsunami" },
  { src: pokyumImg, comment: "폭염", path: "heatwave" },
  { src: hwasanImg, comment: "화산", path: "volcanic" },
];
export const question = {
  earthquake: [
    {
      quiz_id: "tasdf",
      content: "ㅅㄷㄴㅅ",
      image_url: "ㅁㄴㅇㄹ",
      type: "OX",
      correct_rate: 20.34,
    },
    {
      quiz_id: "tasdf",
      content: "ㅅㄷㄴㅅ",
      image_url: "ㅁㄴㅇㄹ",
      type: "ANSWER",
      correct_rate: 20.34,
    },
    {
      quiz_id: "tasdf",
      content: "ㅅㄷㄴㅅ",
      image_url: "ㅁㄴㅇㄹ",
      type: "OX",
      correct_rate: 20.34,
    },
    {
      quiz_id: "tasdf",
      content: "ㅅㄷㄴㅅ",
      image_url: "ㅁㄴㅇㄹ",
      type: "OX",
      correct_rate: 20.34,
    },
    {
      quiz_id: "tasdf",
      content: "ㅅㄷㄴㅅ",
      image_url: "ㅁㄴㅇㄹ",
      type: "ANSWER",
      correct_rate: 20.34,
    },
  ],
  thunderstroke: [],
  flood: [],
  landslide: [],
  drought: [],
  typhoon: [],
  gale: [],
  coldwave: [],
  duststorm: [],
  tsunami: [],
  heatwave: [],
  volcanic: [],
};
